# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty #local
#prod:permalink:  /:year/:month/:title

# Setup
title:            'd4tagirl'
tagline:          'Daniela Vazquez'
description:      'A Blog about a girl finding her place in the Data Science world'
meta_description: 'A Blog about a girl finding her place in the Data Science world. I''m particularly interested in Machine Learning, the R Programming Language and its community'
meta_tags:        ['blog', 'r', 'rstats', 'data science', 'daniela vazquez', 'RLadies', 'NASA Datanaut', 'machine learning']
url:              https://d4tagirl.com

author:
  name:           'Daniela Vazquez'
  url:            https://twitter.com/intent/tweet?user_id=114258616
  email:          daniela.vazquez@gmail.com

paginate:         30
excerpt_separator: <!--more-->

extlinks:
  attributes: {rel: nofollow, target: _blank}
#prod:  check_links: true
  check_exclude: ['twitter.com', 'disqus.com']

page_gen:
  - data: tags
    template: tag
    name: tag
    dir: tags

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]
